### ISSUE TITLE
Задание 7 (программное - строки из 0 и 1)

### ISSUE THREAD

**Issue by MikhailovAlexander** [HSE-algo-23-owl/programming_tasks#64]
# Задание №7  
## Задача на взаимную рекурсию (строки из 0 и 1) + биномиальный коэффициент
1. В файле main.py реализовать функцию *generate_strings*, принимающую длину строки и возвращающую список строк заданной длины, состоящих из нулей и единиц, в которых нули не соседствуют друг с другом.
2. В файле main.py реализовать функцию *binomial_coefficient*, принимающую два числа n и k и возвращающую значение биномиального коэффициента C из n по k. Вычисление коэффициента необходимо реализовать **как рекурсивно, так и итеративно**. Для вычисления коэффициента использовать функцию 

$$
C^k_n=C^k_{n-1}+C^{k-1}_{n-1}
$$

## Примечания
- Для реализации функции *generate_strings* использовать **взаимную рекурсию**.
- Для функции *binomial_coefficient* параметр **use_rec определяет использовать рекурсивную реализацию или итеративную**, значение по умолчанию False, то есть используется итеративная реализация.
- Разработку вести в отдельной ветке, созданной на основе данной. В названии ветки префикс main заменить на название команды.
- Корректность работы функции *generate_strings* проверить запустив файл test.py с модульными тестами.
- Корректность работы функции binomial_coefficient проверить запустив файл test.py с модульными тестами.

## Биномиальные коэффициенты  
  
Биномиальный коэффициент $C^k_n$ равен числу сочетаний из n по k. Может быть 
вычислен по формуле:

$$
C^k_n=\frac{n!}{k!(n-k)!}
$$

Для указанной формулы можно вынести за скобки $\frac{n}{k}$ и получить:

$$
C^k_n=\frac{n}{k} C^{k-1}_{n-1}
$$

Согласно правилу Паскаля, для любых натуральных чисел *n* и *k*, для которых 
1 ⩽ *k* ⩽ *n* :

$$
C^k_n=C^k_{n-1}+C^{k-1}_{n-1}
$$

**Comment by EugenMusihin** [comment]
Blur программное 2
